### ISSUE TITLE
instruction for get address dump?

### ISSUE THREAD

**Issue by RealKallos** [demmonic/PUBGDL#1]
thx for nice works but the where and how we can get address dump? like for encrypted actor.
i know it's little bit noobsy, but the i need to know this thank you.

**Comment by demmonic** [comment]
I posted on the thread, the dump in my test is from the UWorld offset, which is.. 0x4054650 right now!

Just read an encrypted block from your process from wherever you need to decrypt, and pass it to decrypt.

**Comment by demmonic** [comment]
```
EncryptedBlock block;
read<EncryptedBlock>(&block, addressofuworldorsomethingelse); 
uint64_t decrypted = decrypt_ptr(&block);
```

**Comment by RealKallos** [comment]
thank you sir, have a good day

**Comment by demmonic** [comment]
Let me know if you have any other issues, I'll keep this open until you say it's working.

**Comment by RealKallos** [comment]
Seems to be it works well, but my external trash suddenly can't get encrypted uworld.
it's not caused by decryption i just get 0 when i read GetBase() + 0x4054650.

**Comment by demmonic** [comment]
To clear things up, you shouldn't be able to print the 'encrypted' data, unless you do it as a byte array. Most of its data is 0s, with the pointer data at the end. It's a EncryptedBlock structure, not a pointer.

**Comment by RealKallos** [comment]
Well.. I tried last build of this but problem gets more and more.
Can you check your gmail inbox? i sent a mail to you.
thanks

**Comment by myloft** [comment]
Can any one give me some advice?
Is it all right?
`		int64_t Encrypted_GNames = readType<int64_t>(m_PUBase + 0x3F36940, PROTO_NORMAL_READ);
		init_decryption();
		int64_t GNames = decrypt_ptr<int64_t>((EncryptedBlock*)Encrypted_GNames);`

**Comment by RealKallos** [comment]
struct UWorldptr { };
init_decryption();

	EncryptedBlock *UWorldblock;
	*UWorldblock = m_kReader->readType<EncryptedBlock>(getPUBase() + UWorld, PROTO_NORMAL_READ);

	UWorldptr *decrypted_ptr = decrypt_ptr<UWorldptr*>((EncryptedBlock*)UWorldblock);


for my friend, it will right i also gets other errors so i sent email to demmonic.

**Comment by myloft** [comment]
I got crash when read 0x0xFFFFFFFFFFFFFFFF.
![image](https://user-images.githubusercontent.com/25258169/34926451-8d72daf2-f9ea-11e7-9e17-d940d5ea726e.png)

**Comment by RealKallos** [comment]
yes it's weird, i also trying to get it work. if you got something post it here plz
i also will.

**Comment by demmonic** [comment]
Your code has logic errors. I'm currently using this library in production with no issues.

```
EncryptedBlock *UWorldblock; // what is this?? a random value on the stack???
*UWorldblock = m_kReader->readType<EncryptedBlock>(getPUBase() + UWorld, PROTO_NORMAL_READ);
```
Try this:
```
EncryptedBlock *UWorldblock = m_kReader->readType<EncryptedBlock>(getPUBase() + UWorld, PROTO_NORMAL_READ);
```
If your library supports reading whole structs.

**Comment by myloft** [comment]
Thanks very much.

**Comment by RealKallos** [comment]
Thx for kind explanations :)
me and myloft meet with discord and we get goals! very appreciate!
when you make thread independent for this decryptions, i will +rep you!
its really faster then dummy one!

**Comment by demmonic** [comment]
I probably won't open a thread as I'm far too busy. I'm glad to hear you have it working, open another issue if you require any assistance.
