### ISSUE TITLE
Struct of EncryptedBlock for C# ??

### ISSUE THREAD

**Issue by ventrixcode** [demmonic/PUBGDL#2]
Struct of EncryptedBlock for C# ??

**Comment by demmonic** [comment]
EncryptedBlock is a block of 0x38 longs (64-bit integers.) You could use an array, which is what I do for Java.

**Comment by KariyakiLP** [comment]
```public unsafe struct EncryptedBlock
        {
            public fixed long data[48];
        }```

**Comment by ventrixcode** [comment]
`public unsafe struct EncryptedBlock
        {
            public fixed long data[48];
        }`
